/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module seven_seg_lives_5 (
    input [2:0] lives,
    output reg [6:0] out
  );
  
  
  
  wire [7-1:0] M_digit_lut_out;
  reg [3-1:0] M_digit_lut_in;
  digit_lut_25 digit_lut (
    .in(M_digit_lut_in),
    .out(M_digit_lut_out)
  );
  
  always @* begin
    M_digit_lut_in = lives;
    out = M_digit_lut_out;
  end
endmodule
