/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module multiplexer_23 (
    input [1:0] signal,
    input [24:0] one,
    input [24:0] two,
    input [24:0] three,
    input [24:0] four,
    output reg [24:0] counter
  );
  
  
  
  always @* begin
    
    case (signal)
      1'h0: begin
        counter = one;
      end
      1'h1: begin
        counter = two;
      end
      2'h2: begin
        counter = three;
      end
      2'h3: begin
        counter = four;
      end
      default: begin
        counter = one;
      end
    endcase
  end
endmodule
