/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module seven_seg_score_6 (
    input [7:0] score,
    output reg [6:0] lsb,
    output reg [6:0] msb
  );
  
  
  
  wire [7-1:0] M_digit_lut_lsb_out;
  reg [4-1:0] M_digit_lut_lsb_in;
  digit_lut_lsb_26 digit_lut_lsb (
    .in(M_digit_lut_lsb_in),
    .out(M_digit_lut_lsb_out)
  );
  
  always @* begin
    M_digit_lut_lsb_in = 1'h0;
    lsb = M_digit_lut_lsb_out;
    msb = 7'h00;
    if (score < 4'ha) begin
      msb = 7'h3f;
      M_digit_lut_lsb_in = score;
    end else begin
      if (score < 5'h14) begin
        msb = 7'h06;
        M_digit_lut_lsb_in = score - 8'h0a;
      end else begin
        if (score < 5'h1e) begin
          msb = 7'h5b;
          M_digit_lut_lsb_in = score - 8'h14;
        end else begin
          if (score < 6'h28) begin
            msb = 7'h4f;
            M_digit_lut_lsb_in = score - 8'h1e;
          end else begin
            if (score < 6'h32) begin
              msb = 7'h66;
              M_digit_lut_lsb_in = score - 8'h28;
            end else begin
              if (score < 6'h3c) begin
                msb = 7'h6d;
                M_digit_lut_lsb_in = score - 8'h32;
              end else begin
                if (score < 7'h46) begin
                  msb = 7'h7d;
                  M_digit_lut_lsb_in = score - 8'h3c;
                end else begin
                  if (score < 7'h50) begin
                    msb = 7'h07;
                    M_digit_lut_lsb_in = score - 8'h46;
                  end else begin
                    if (score < 7'h5a) begin
                      msb = 7'h7f;
                      M_digit_lut_lsb_in = score - 8'h50;
                    end
                  end
                end
              end
            end
          end
        end
      end
    end
  end
endmodule
