/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module boolean_unit_12 (
    input [5:0] alufn,
    input [15:0] a,
    input [15:0] b,
    output reg [15:0] out
  );
  
  
  
  always @* begin
    
    case (alufn[0+3-:4])
      4'h8: begin
        out = a & b;
      end
      4'he: begin
        out = a | b;
      end
      4'h6: begin
        out = a ^ b;
      end
      4'ha: begin
        out = a;
      end
      4'h9: begin
        out = !(a & b);
      end
      4'hf: begin
        out = !(a | b);
      end
      4'h7: begin
        out = !(a ^ b);
      end
      4'hb: begin
        out = b;
      end
      4'hc: begin
        out = a & !b;
      end
      4'hd: begin
        out = !a & b;
      end
      4'h4: begin
        out = a | !b;
      end
      4'h5: begin
        out = !a | b;
      end
      4'h2: begin
        out = !a;
      end
      4'h3: begin
        out = !b;
      end
      4'h1: begin
        out = 16'h0000;
      end
      default: begin
        out = 16'h0001;
      end
    endcase
  end
endmodule
